### ISSUE TITLE
Make setResponseData optional

### ISSUE THREAD

**Issue by michal-duda** [vadim-klimov/apache-jmeter-listener-elasticsearch#3]
Some our API calls returns quite big responses. We don't want to store these big responses in Elasticsearch, it is causing us problems with ES and Kibana. We are interested only in response code and time. Could you make this line of code configurable? Some switch which would allow us not upload response data:

    sampleResult4Visualizer.setResponseData(sampleResult.getResponseDataAsString());

**Comment by vadimklimov** [comment]
Hello Michal,

For time being, I would suggest forking the source code, commenting out corresponding code line and rebuilding the plugin. In many use cases I can think of, persisting and indexing complete response can be useful and helpful in analysis of executed test case.

AbstractBackendListenerClient is limited in presentation of configurable options in JMeter's UI - hence, implementation of support for omitting specific attributes of sample result can be configured, but not in a very user-friendly way, in my taste: for example, by enumerating delimited names of attributes which shall be omitted.

Regards,
Vadim

**Comment by michal-duda** [comment]
Hello @vadim-klimov,

Yes that's what I did. It is just a suggestion for future to implement some setting for this.

Regards,
Michal
