### ISSUE TITLE
Index is not getting created with elastic search and kibana v5.5

### ISSUE THREAD

**Issue by Amaradana** [vadim-klimov/apache-jmeter-listener-elasticsearch#5]
I tested this with 5.4.3 when i ran my test from kibana i was able to get index recognized, but with 5.5 this is not be recognized., i dont see any errors in jmeter

**Comment by vadimklimov** [comment]
Hi,

Can you check in Elasticsearch (using Elasticsearch indices and documents get APIs or any other tool that you use for Elasticsearch indices content monitoring), if you got index created and documents created in that index? I would suggest checking this not using Kibana, but using Elasticsearch tools, to ensure that the index and documents in it have been created or not.

If you don't find index / documents, please enable verbose logging (DEBUG log level) in JMeter to get more details on queries sent by JMeter's Elasticsearch listener to Elasticsearch server, and responses returned by Elasticsearch server - this shall bring extra details that will be helpful for investigation.

It will also be helpful to see if there are any errors produced by Elasticsearch for calls coming from JMeter, if you have access to Elasticsearch logs.

Regards,
Vadim

**Comment by Amaradana** [comment]
Finally i found the issue, First with 5.5 security is enabled for both kibana and elastic search and on top of it i also installed xpack in elstic searcha nd kibana, I had to turn off my x-pack security level 
"xpack.security.enabled: false" in elasticsearch.yml.

Though i am pretty new to both most off things you said did not get into my head, as i tried to build a comparison report in influxdb and grafana which never allowed me to do. So i found i can do a comparison report but still struggling for lot off columns that i am trying to add for instance vusers, banging my head to get this number and in comparison report different of avg for 2 _types. 

If you have any dashboard if you can share that would be helpful. 

And this issue can be closed.
