### ISSUE TITLE
Ability to extend the result package.

### ISSUE THREAD

**Issue by slawomirsepiol** [vadim-klimov/apache-jmeter-listener-elasticsearch#6]
Hello Vadim,

First of all, thanks for creating and releasing the plugin - it's easy to use and works great!

What I need to do in my project is to send more fields to elasticsearch to have custom tags to filter by. I've made some improvements that work for me and I'm now wondering if you'd be ok with me contributing to the plugin. If so, I can create a PR for you to review.

Best Regards,
Slawomir

**Comment by vadimklimov** [comment]
Hello Slawomir,

Thank you for kind words. Yes, you are very welcome to contribute if you see there are missing features that are worth assessing and considering for incorporation into the plugin functionality. I appreciate a lot both any kind of feedback that helps me to analyze and evaluate feasibility of implementation of demanded features, as well as if you already have implementation ideas / realization for it that can be looked at.

Regards,
Vadim
