### ISSUE TITLE
Add proxy server settings to Elasticsearch parameters

### ISSUE THREAD

**Issue by rbourga** [vadim-klimov/apache-jmeter-listener-elasticsearch#7]
Hi Vadim,
in the list of parameters of the Elasticsearch listener (protocol. host, port etc.), could you add parameters for a proxy to be used by the Elasticsearch Java REST library? Parameters would be:
ProxyServerNameOrIP
ProxyPortNumber
ProxyUsername
ProxyPassword
Thanks.

**Comment by vadimklimov** [comment]
Hello Robert,

Thank you for feedback and suggestion. Proxy support has been introduced in the version 0.3. To configure proxy settings in the listener (proxy server's URL and user/password in case proxy authentication is required), three additional parameters (elasticsearch.connection.proxy.*) have been introduced - please refer to the README page for explanation of their usage.

Regards,
Vadim
